title: Dear Mamma: Letters from Camp Lee, VA (1918)
email: jwr@illinois.edu
description: by John Randolph

baseurl: "/MinDocMini" # the subpath of your site. Change it if the name of your repository is other than "mindoc"

twitter_username: jekyllrb
github_username:  jekyll

# Build settings

plugins:
  - jekyll-feed

collections:
  mindoc_media:
    output: true
    layout: 'image_description'
